### ISSUE TITLE
Blank Square with no lyrics

### ISSUE THREAD

**Issue by JosephInn** [71/ytm-lyrics#2]
Is this for personal use only?, or is it ready for public use?
I love the way it integrates with YouTube Music, but as of yet it hasn't shown any lyrics, I've tried multiple songs. And I tested in both Chrome and Firefox with the same result.

**Comment by JosephInn** [comment]
I'm a moron, sorry. It's working now =). Thanks so much for making this!

**Comment by 71** [comment]
I'm glad you managed to sort it out. Out of curiosity, what was the issue? Maybe I can clarify some steps.

**Comment by JosephInn** [comment]
Well, I thought I could use TamperMokey instead of ViolentMonkey (but it didn't work), then I went to Firefox and used it with GreaseMonkey (which still didn't work for some reason), after that I remembered you suggested specifically ViolentMonkey (now its working perfectly).

*can I disable autoscroll somehow? (without disabling the highlight on the current verse)

**Comment by 71** [comment]
Weird. I expected TamperMonkey to work, and GreaseMonkey should work when renaming `GM_{xmlHttpRequest,getValue,setValue}` to `GM.{xmlHttpRequest,getValue,setValue}`. I've only tried ViolentMonkey myself though.

I haven't implemented that yet, but it should be doable, gimme a sec.

**Update**: with c92eaa940aaea2f1fed71bceabac9d8c46916bb5 it should also work on TM / GM, and you can toggle autoscroll with S.

**Comment by JosephInn** [comment]
Ok, you're awesome =,) thank you so much!
.
.
.
*by the way, you're french right?, I've been learning french for about two months now, and oh wow, it's going to be a bumpy ride (I know this has nothing to do with anything, but one doesn't meet french people everyday =\  , haha nice to meet you Gregoire)

**Comment by 71** [comment]
No problem. Please tell me if you have any more issues.

--------------

Yep, and yes it's not going to be easy. If that's any consolation, we all make mistakes and even though a lot of people are very strict when it comes to grammar, many others will be forgiving. I notice (and even make) grammar errors in "official" documents and emails fairly often, despite them being written by native French speakers.

In the end though, I think it will get very satisfying to understand sentences and express yourself in French once you get the knack of it, so good luck! Plus you'll realize that a lot of English words come from French and vice-versa.
